# Copyright (c) 2026 — Proyecto académico Invernadero.
# CI básico: compila con Maven en cualquier push (repo greenhouse-back).

name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Build
        run: mvn -B package -DskipTests
